name: statomat
on:
  issues:
    types: [labeled]
jobs:
  setstatus:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.issue.labels.*.name, 'base')}}
    steps:
      - name: Find component label
        id: component-label
        run: |
          issue_labels = ${{ github.event.issue.labels }}
          for label in $issue_labels; do
            if [[ $label == component:* ]]; then
              echo $label >> $GITHUB_OUTPUT
              exit 0
            fi
          done

      - name: Find base issue
        id: base-issue
        run: |
          LABEL1= ${{ steps.component-label.outputs.output1 }}
          LABEL2='base'
          ISSUE_SEARCH_RESULT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/search/issues?q=label:$LABEL1+label:$LABEL2)
          echo $ISSUE_SEARCH_RESULT